---
- name: Copy artifact to EC2
  copy:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Start server
  shell: |
    cd /home/ubuntu/
    tar -xvf artifact.tar.gz
    npm install
    pm2 stop npm
    sudo pm2 start npm -- start
